question_data = [
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Great Wall of China is visible from the moon.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Video streaming website YouTube was purchased in it's "
        "entirety by Facebook for US$1.65 billion in stock.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The sum of all the numbers on a roulette wheel is 666.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Nutella is produced by the German company Ferrero.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "An eggplant is a vegetable.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The bikini is named after the Bikini Atoll, an island where the United States conducted "
        "tests on atomic bombs.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "You are allowed to sell your soul on eBay.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Ananas is mostly used as the word for Pineapple in "
        "other languages.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The term Spam came before the food product Spam.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The French word to travel is Travail",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Adolf Hitler was born in Australia. ",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The French word for glass is glace.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "hard",
        "question": "In Scandinavian languages, the letter å means river.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "One of Donald Trump's 2016 Presidential Campaign promises was to build a border wall between the "
        "United States and Mexico.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Fast food restaurant chains Carl's Jr. and Hardee's are owned by the same company.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Scotland voted to become an independent country during the referendum from September 2014.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The scientific name for the Southern Lights is Aurora Australis?",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The National Animal of Scotland is the Unicorn.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Haggis is traditionally ate on Burns Night.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Francis Bacon died from a fatal case of pneumonia while he was "
        "attempting to preserve meat by stuffing a chicken with snow.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The commercial UK channel ITV stands for International Television.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Vietnam's national flag is a red star in front of a yellow background.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A pasodoble is a type of Italian pasta sauce.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo. "
        "is a grammatically correct sentence.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Slovakia is a member of European Union-",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
]
